# Chief - Autonomous agent loop for PRDs with Ollama Code
# Homebrew formula for installing chief on macOS and Linux
#
# Installation Options:
#
# Option 1: Use the tap (recommended after first release)
#   brew tap izdrail/chief
#   brew install chief
#
# Option 2: Install directly from this repo
#   brew install izdrail/chief
#
# Option 3: Build from source
#   brew install --build-from-source izdrail/chief
#
# Note: This file is auto-generated by goreleaser during releases.
# The SHA256 checksums below are placeholders until the first release.

class Chief < Formula
  desc "Autonomous agent loop for working through PRDs with Claude Code"
  homepage "https://github.com/izdrail/chief"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/izdrail/chief/releases/download/v#{version}/chief_#{version}_darwin_amd64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_DARWIN_AMD64_SHA256"

      def install
        bin.install "chief"
      end
    end

    on_arm do
      url "https://github.com/izdrail/chief/releases/download/v#{version}/chief_#{version}_darwin_arm64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_DARWIN_ARM64_SHA256"

      def install
        bin.install "chief"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/izdrail/chief/releases/download/v#{version}/chief_#{version}_linux_amd64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"

      def install
        bin.install "chief"
      end
    end

    on_arm do
      url "https://github.com/izdrail/chief/releases/download/v#{version}/chief_#{version}_linux_arm64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_LINUX_ARM64_SHA256"

      def install
        bin.install "chief"
      end
    end
  end

  test do
    # Verify the binary runs and reports its version
    assert_match version.to_s, shell_output("#{bin}/chief --version")
  end
end
